### ISSUE TITLE
If statement error in search.trend

### ISSUE THREAD

**Issue by moisesbernabeu** [cran/RRphylo#1]
I was running a **reanalysis** for a multitrait matrix and two nodes with the following command:
```{R}
RR <- RRphylo(tree = tree, y = traits)
result <- search.trend(RR = RR, y = traits, nsim = 100,
                       node = c(200, 357), clus = cc, cov = NULL)
```
I started with 100 simulations to test, but when I run the result, I get the following error
```
Error in if (p.rate.comp[[j]][i, 7] <= 0.05) { : 
  missing value where TRUE/FALSE needed
```
I checked the data and the tree, they are common, and without NAs or "strange" values. How could I solve this?

Versions:
```
> R.version.string
[1] "R version 4.1.2 (2021-11-01)"

> packageVersion('RRphylo')
[1] ‘2.7.0’
```

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by moisesbernabeu** [comment]
Thanks a lot!
